### ISSUE TITLE
Which package should I use?

### ISSUE THREAD

**Issue by ackvf** [Hoffs/vscode-versionlens#13]
Hi, since you adopted the original logo, name and versioning, does it mean that the original extension is no longer maintained?(1) Why have you not provided this as a PR to the upstream instead?(2) Do you plan to stay in sync with it?(3) Do you plan to actively maintain this fork?(4) If I only use npm, are both extensions equal?(5)

**Comment by Hoffs** [comment]
Didn't really adopt anything, just forked the base package and published under my account with the notice about the changes as I needed to use the package. Also you could check base repo and see that I have two stale PR's with changes from here (as the original author seems MIA):
https://github.com/vscode-contrib/vscode-versionlens/pull/165
https://github.com/vscode-contrib/vscode-versionlens/pull/170

As for actively maintaining it, not sure, I only looked after C# part that as that's the one I use myself (as written in updated readme/notice).

**Comment by ackvf** [comment]
I see, so anyway, if you don't plan to actively maintain it other than the parts you yourself use, I should be fine using either of the two, since I only use npm, right. Too bad the original repo doesn't accept PR.

Thanks for answers.
