### ISSUE TITLE
Is this duplicate exention needed any more?

### ISSUE THREAD

**Issue by pflannery** [Hoffs/vscode-versionlens#17]
@Hoffs 

Can you unpublish this? 

I believe the original reason for this extension has now be resolved in the latest version lens and seeing as it has a duplicate extension name it can be confusing when searching the marketplace. (I once installed this by mistake myself lol)

Would be much appreciated

**Comment by Hoffs** [comment]
Which issue you think resolved it? The main fix for me here is the use of multiple custom resolvers ( https://github.com/Hoffs/vscode-versionlens/blob/master/src/providers/dotnet/nugetClient.js#L19 ) and not relying on single nuget service 
`PackageBaseAddress`. The private nuget repository that I am using does not implement that service thus I can't use that extension.

I can try republishing it under different name or something.

**Comment by pflannery** [comment]
Versionlens now automatically retrieves nuget source feeds using the output of `dotnet nuget list source` command.
Can also specify custom sources in the "versionlens.dotnet.nuget.sources" setting.

>I can try republishing it under different name or something.

If it isnt yet resolving your issue then yes having a different name variation would be better. thanks

**Comment by Hoffs** [comment]
Updated the name/description to include that this is unmaintained https://marketplace.visualstudio.com/items?itemName=Hoffs.vscode-versionlens
